# Generated by Django 2.2.7 on 2019-12-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('years_old', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
