# Generated by Django 2.2.7 on 2019-12-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='years_old',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
