# Generated by Django 2.2.7 on 2019-12-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=1000000, primary_key=True, serialize=False),
        ),
    ]
