# Generated by Django 2.2.7 on 2019-12-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='global_position',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='local',
            name='local_position',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
