# Generated by Django 2.2.7 on 2019-12-15 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191215_1120'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='global',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lacal',
            name='user',
        ),
        migrations.AddField(
            model_name='global',
            name='global_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_of_user', to='users.User'),
        ),
        migrations.AddField(
            model_name='lacal',
            name='local_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_of_user', to='users.User'),
        ),
    ]
